# Generated by Django 2.1.5 on 2019-01-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mkpro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('local', models.CharField(choices=[('UFRN', 'Universidade Federal do Rio Grande do Norte'), ('UERN', 'Universidade Estadual do Rio Grande do Norte'), ('IFRN', 'Instituto Federal de Educação Ciência e Tecnologia do Rio Grande do Norte')], max_length=4)),
                ('stars', models.CharField(choices=[('1', '1 ESTRELA'), ('2', '2 ESTRELAS'), ('3', '3 ESTRELAS'), ('4', '4 ESTRELAS'), ('5', '5 ESTRELAS')], max_length=1)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
