# Generated by Django 2.1.5 on 2019-01-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mkpro',
            old_name='local',
            new_name='institution',
        ),
        migrations.AlterField(
            model_name='mkpro',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
