# Generated by Django 2.1.5 on 2019-01-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20190114_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mkpro',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
