# Generated by Django 2.1.5 on 2019-01-14 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190114_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mkpro',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
